#!/bin/bash
echo ""
echo""
clear
echo""
echo -e "\e[1;96m===================================================== > > >\e[m "
echo " "
printf "\e[1;31m[\e[0m\e[1;92m01\e[0m\e[1;31m] \e[0m\e[1;37;44m Termux \e[0m  "  
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"     
echo
printf "\e[1;31m[\e[0m\e[1;92m02\e[0m\e[1;31m] \e[0m\e[1;37;41m Linux \e[0m   "  
echo
printf "\e[1;31m\e[0m\e[1;92m\e[0m\e[1;31m \e[0m\e[1;37;44m\e[0m"
echo " "
echo -e "\e[1;96m===================================================== > > >\e[m "
echo ""
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m You Want to Choose Un-install System : \e[1;91m (1/2)  : \e[0m' option
echo""
echo""
echo""
if [[ $option == *'1'* ]]; then
echo""
clear
echo ""
echo -e ""
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;33m\e[0m\e[1;90m\e[0m\e[1;92m  !!             Uninstall Tool           !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ---------------------------------------- \e[1;91m\e[0m'
echo ""
echo ""
echo ""
sleep 7
cd /data/data/com.termux/files/usr/bin
rm -rf FreeFire Run-Ngrok OnlineHacking FreeFire-Phishing ngrok cloudflared
cd /data/data/com.termux/files/usr/bin/.SUMAN
rm -rf 1 2 3 4 5 6 7 8 9 0
rm -rf FreeFire Run-Ngrok OnlineHacking FreeFire-Phishing ngrok cloudflared
cd /data/data/com.termux/files/home
rm -rf FreeFire-Phishing

echo -e ""
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;33m\e[0m\e[1;90m\e[0m\e[1;92m  !!         Successfully Uninstall       !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ---------------------------------------- \e[1;91m\e[0m'
echo ""
echo ""
exit

fi
if [[ $option == *'2'* ]]; then
echo""
clear
echo ""
echo -e ""
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;33m\e[0m\e[1;90m\e[0m\e[1;92m  !!             Uninstall Tool           !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ---------------------------------------- \e[1;91m\e[0m'
echo ""
echo ""
echo ""
sleep 7
cd /usr/bin
rm -rf SUMAN FreeFire Run-Ngrok OnlineHacking FreeFire-Phishing ngrok cloudflared
rm -rf .SUMAN/1/ .SUMAN/2/ .SUMAN/3/ .SUMAN/4/ .SUMAN/5/ .SUMAN/6/ .SUMAN/7/ .SUMAN/8/ .SUMAN/9/ .SUMAN/0/
cd /root
rm -rf FreeFire-Phishing

echo -e ""
echo ""
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ----------------------------------------  \e[1;91m\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;33m\e[0m\e[1;90m\e[0m\e[1;92m  !!         Successfully Uninstall       !!\e[0m'
echo -e $'\e[1;91m\e[0m\e[1;91m\e[0m\e[1;96m\e[0m\e[1;91m   ---------------------------------------- \e[1;91m\e[0m'
echo ""
echo ""
exit
fi
